### ISSUE TITLE
"Icon could not be loaded" when not on root path

### ISSUE THREAD

**Issue by ThatOneCalculator** [LyonSyonII/astro-preload#3]
Attempting to load an icon that isn't on the root path results in this:

![image](https://github.com/LyonSyonII/astro-preload/assets/44733677/003f1efb-b1ab-4cf7-ac3f-844e9a7f4282)

Versus on the root (still has problems, see the black color instead of active color):

![image](https://github.com/LyonSyonII/astro-preload/assets/44733677/9cec6cd3-4f49-4020-a2b9-6cef681c965f)

**Comment by ThatOneCalculator** [comment]
Same thing happens with images

![image](https://github.com/LyonSyonII/astro-preload/assets/44733677/df2413ea-9bfc-4b2f-81cb-980f2260ba8b)

**Comment by LyonSyonII** [comment]
"Icon could not be loaded" should be fixed with #2, will look into the active color problem, but it seems like an unrelated error.

**Comment by LyonSyonII** [comment]
Version `1.1.2` is now published, could you try it and see if it solves the problem?

**Comment by ThatOneCalculator** [comment]
Yep, that seemed to fix it. I'll make another issue for the icon active color soon
